### ISSUE TITLE
Property Name "Items" is invalid

### ISSUE THREAD

**Issue by cliveseldon** [go-openapi/validate#108] opened 2019-04-13 10:54 UTC
If you have a property name "items" it fails validation. I added to schema_test.go:

```
func TestSchemaValidator_itemsAsProperty(t *testing.T) {
	var schemaJSON = `
{
	"properties": {
    "foo": {
      "type": "string"
    },
		"items": {
       "type": "string"
    }
	}
}`

	schema := new(spec.Schema)
	require.NoError(t, json.Unmarshal([]byte(schemaJSON), schema))

	var input map[string]interface{}
	var inputJSON = `{"foo":"bar","items":"hello"}`
	assert.NoError(t, json.Unmarshal([]byte(inputJSON), &input))

	// ok
	s := NewSchemaValidator(schema, nil, "", strfmt.Default, DisableObjectArrayTypeCheck(true))
	result := s.Validate(input)
	assert.True(t, result.IsValid())

	// Should be still ok
	s = NewSchemaValidator(schema, nil, "", strfmt.Default)
	result = s.Validate(input)
	assert.True(t, result.IsValid())

}
```

```
API server listening at: 127.0.0.1:45939
=== RUN   TestSchemaValidator_items
--- FAIL: TestSchemaValidator_items (145.61s)
    schema_test.go:249: 
        	Error Trace:	schema_test.go:249
        	Error:      	Should be true
        	Test:       	TestSchemaValidator_items
FAIL
```

**Comment by fredbi** [comment] 2019-04-13 12:27
duplicate of #43

**Comment by cliveseldon** [comment] 2019-04-14 07:01
In the test above you would think this fuction:
https://github.com/go-openapi/validate/blob/3fd099a3cf2ee54e86beee561afe8f1b5bfe769e/object_validator.go#L54-L57
should return true and thus as its called from
https://github.com/go-openapi/validate/blob/3fd099a3cf2ee54e86beee561afe8f1b5bfe769e/object_validator.go#L69-L71
all should be ok. But in reality it returns `false` as `o.Path` is ""

Is this correct?

**Comment by fredbi** [comment] 2019-04-14 09:08
not that simple...

This piece of code should not actually be in charge of checking swagger stricter constraints but should only validate jsonschema constraints

**Comment by cliveseldon** [comment] 2019-04-14 09:13
Thanks for your update @fredbi . 

My comment is really trying to gauge how much and what work is required to fix this issue.

**Comment by tossmilestone** [comment] 2019-05-22 09:05
@cliveseldon I have submitted a PR to fix the issue, you can check it #106.

**Comment by cliveseldon** [comment] 2019-10-09 06:57
This is great. When will it be in a k8s release so we can check this has reached upstream?

**Comment by tossmilestone** [comment] 2019-10-10 03:11
@cliveseldon it seems that you found a bug of the structural schema feature. In the PR https://github.com/kubernetes/kubernetes/pull/76124, the CRD validation have been added by the option.

**Comment by fredbi** [comment] 2019-10-10 09:09
This has been a long standing bug. The culprit is here https://github.com/go-openapi/validate/blob/cae306c30a7752481df7cfb7a7340d1e85fa64d6/object_validator.go#L60

**Comment by cliveseldon** [comment] 2019-10-10 09:42
@fredbi But this sounds very much like the original bug of this issue which is if you have a property called "items" its always treating this as an array. I thought the fix was specifically to solve this?

**Comment by fredbi** [comment] 2019-10-10 11:33
There are 2 issues related with items and people are sometimes confusing. The root cause is the same but the symptom are two-fold:
i) a swagger-specific rule to validate "items" for arrays (i.e. arrays must have items) has slipped into the generic json-schema code
ii) this rule (code ref mentioned above) is lazy and checks that everything that has an "items" key must be an array, which is obviously wrong

This is at least my understanding of the code and unfortunately I did not find the time to fix it (it was here well before I even started contributing here...).

**Comment by fredbi** [comment] 2019-10-10 11:42
I am failing to see how #107 could solve this bug. IMHO, this is fixing some other thing

**Comment by cliveseldon** [comment] 2019-10-11 13:24
I think actually the api-server crash I logged above is due to ` x-kubernetes-int-or-string` handling (see https://github.com/kubernetes/kubernetes/issues/83778 ) rather than #107

**Comment by cliveseldon** [comment] 2019-11-06 22:12
I don't think this is fixed. See https://github.com/kubernetes/kubernetes/issues/84880

**Comment by fredbi** [comment] 2019-11-06 22:47
@cliveseldon PR #119 should fix this.

**Closed** 2019-11-06 22:51 UTC
Labels: bug, duplicate, pending PR
