### ISSUE TITLE
Empty schemes list is not allowed in openAPI spec

### ISSUE THREAD

**Issue by mbohlool** [go-openapi/validate#5] opened 2016-08-15 01:59 UTC
The validation passes for Specs with empty "schemes" list. Valid values are defined in "schemesList" section of swagger 2.0 schema at http://swagger.io/v2/schema.json and empty is not one of them.

**Comment by BafFlynN** [comment] 2016-09-30 20:11
@mbohlool I am not apart of this group but I will send a pull req soon with both of your fixes and I verify on the Spec.

**Comment by GlenDC** [comment] 2016-12-23 04:39
@BafFlynN are you still working on this?

**Comment by GlenDC** [comment] 2016-12-27 01:54
As far as  I can see, an empty `schemes` list is acceptable. It validates also in the swagger editor. On top of that you can read this in the OpenAPI spec markdown version:

> If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself.

Source: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object

So @casualjim I think you can close this issue?

**Comment by casualjim** [comment] 2016-12-27 03:02
I think the issue is that the value of schemes can be an empty list, and an empty list is not allowed.
schemes can be missing from the json document, they can be null but they can't be an empty list

**Comment by GlenDC** [comment] 2016-12-27 14:59
But why consider that an issue, semantically an empty list, and no list at all, are the same, no?

@casualjim if you want this to be fixed, I can look into it though. Where exactly does it say that an empty list is not allowed, because if so, than the swagger editor will need a PR too, as it doesn't invalidate an empty list given for schemes either.

**Closed** 2016-12-27 16:46 UTC
Labels: wontfix
